const testModules = [
  "./storage/in-memory-repositories.test.js",
  "./storage/in-memory-provider-http-cache-repository.test.js",
  "./storage/in-memory-library-import-repository.test.js",
  "./storage/sqlite-canonical-store.test.js",
  "./storage/sqlite-collection-repository.test.js",
  "./storage/sqlite-library-import-repository.test.js",
  "./storage/sqlite-provider-http-cache-repository.test.js",
  "./plugins/plugin-registry.test.js",
  "./canonical/canonical-store.test.js",
  "./collection/collection-service.test.js",
  "./library_import/library-import-service.test.js",
  "./events/event-service.test.js",
  "./effects/effect-boundary.test.js",
  "./memory/memory-service.test.js",
  "./knowledge/music-knowledge.test.js",
  "./source/source-grounding.test.js",
  "./material_resolve/material-resolve.test.js",
  "./providers/netease-source-provider.test.js",
  "./providers/netease-platform-library-provider.test.js",
  "./providers/musicbrainz-knowledge-provider.test.js",
  "./plugins/plugin-packaging.test.js",
  "./server/server-http-mcp.test.js",
  "./server/server-runtime.test.js",
  "./stage_core/stage-core-factory.test.js",
  "./stage/stage-modules.test.js",
  "./surfaces/mcp-server.test.js",
  "./stage_interface/stage-interface-dispatch.test.js",
  "./stage_interface/stage-interface.test.js",
  "./integration/canonical-persistence.test.js",
  "./integration/collection-runtime.test.js",
  "./integration/library-import-runtime.test.js",
  "./integration/mvp-slice.test.js",
];

for (const testModule of testModules) {
  await import(testModule);
}
