import assert from "node:assert/strict";
import { decryptQrcBlocks, qrcDecrypt } from "../../src/extension/plugins/qq_qrc_decrypt.js";
// Ground-truth vectors generated by the reference Python implementation
// (L-1124/QQMusicApi qqmusic_api/algorithms/tripledes.py). QQ's QRC 3DES is a
// non-standard variant (PC-2 deviation), so these vectors are the correctness
// contract: the TypeScript port must decrypt them byte-for-byte. Node's
// built-in `des-ede3` cannot (verified), which is why the variant is ported.
// LAYER 1 — Triple-DES (EDE3) single-block decrypt. Each pair is
// [plaintext_8bytes_hex, ciphertext_8bytes_hex] produced by Python ENCRYPT.
const blockVectors: ReadonlyArray<readonly [
    string,
    string
]> = [
    ["0000000000000000", "a27b02aa779bf226"],
    ["ffffffffffffffff", "4b789c44381642a3"],
    ["5445535454455354", "c1108fb119189054"],
    ["3132333435363738", "015ea69c23303cee"],
    ["4142434445464748", "fe1dd2e23bbba6e8"],
    ["0001020304050607", "ce92cac4ea3c8406"],
    ["0706050403020100", "181998e019b57041"],
    ["8040201008040201", "2e6863898d5684cf"],
    ["0123456789abcdef", "6c6467a1fc44c95b"],
    ["fedcba9876543210", "fe4d1474607de847"],
];
for (const [plaintextHex, ciphertextHex] of blockVectors) {
    const decrypted = decryptQrcBlocks(Buffer.from(ciphertextHex, "hex"));
    assert.equal(decrypted.toString("hex"), plaintextHex, `QQ QRC 3DES block decrypt must match Python ground truth for ${ciphertextHex}`);
}
// LAYER 2 — End-to-end qrcDecrypt: hex → 3DES → zlib inflate → UTF-8.
// Each pair is [plaintext_utf8, ciphertext_hex] from a Python qrc round-trip
// (utf-8 → zlib compress → zero-pad to 8-byte boundary → 3DES encrypt → hex).
const qrcVectors: ReadonlyArray<readonly [
    string,
    string
]> = [
    ["[ti:Test]\nHello world", "1eaa9479b9b1b2f5af04f8c211f7bfbe66ee93bfa52973bf7ae11bba800f94ce"],
    ['<?xml version="1.0"?><QrcInfos><QrcTrackInfo><![CDATA[test]]></QrcTrackInfo></QrcInfos>', "0c8d67dd3e549974b64ed2680459f138553fe2b7cdeb268e33263ce3ef746059f2628a3253b31f06c2ff0793df22e541ff85ab88366690c3a7d36f240b49f943131bb33124ba5985"],
    ["AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "8e76347abdf721e007ac02bee1089008"],
    ["[00:01.00]line one\n[00:03.50]line two\n", "32dabb4c5e9846fa2d6d1520057b0f98020fccaff3401fe57dd268eb87ba2d201a238e7d666de619"],
];
for (const [text, hex] of qrcVectors) {
    assert.equal(qrcDecrypt(hex), text, `QQ QRC end-to-end decrypt must match Python ground truth for ${text.slice(0, 24)}`);
}
// Raw-byte input path mirrors the hex-string path.
const [firstText, firstHex] = qrcVectors[0]!;
assert.equal(qrcDecrypt(Buffer.from(firstHex, "hex")), firstText);
// Malformed ciphertext is rejected loudly, never silently accepted.
assert.throws(() => decryptQrcBlocks(Buffer.alloc(0)), /non-empty/);
assert.throws(() => decryptQrcBlocks(Buffer.alloc(7)), /multiple of 8/);
